### ISSUE TITLE
[Bug] Dragging app into folder OR over folder causes the folder to disappear.

### ISSUE THREAD

**Issue by devipasigner** [NightwindDev/BoldersReborn#2]
Hello, I have discovered another bug with this tweak. Whenever this tweak is enabled, and I drag an app into a folder OR if it is hovered over a folder, it causes the folder to temporarily disappear (back after a respring). I have experienced this same exact issue with another folder tweak in the past (Folded).

Device Specifications:
Model: A11
Jailbreak: latest palera1n nightly w/ Rootful
Version: 16.5 beta 4

**Comment by NightwindDev** [comment]
Can you send a screen recording of this issue?

**Comment by devipasigner** [comment]
So turns it this was caused by some other tweak I had installed.

**Comment by NightwindDev** [comment]
What tweak was this, out of curiosity?

**Comment by devipasigner** [comment]
I'm certain that it is snowboard causing this.

**Comment by NightwindDev** [comment]
I have Snowboard installed on Dopamine and I don't have that issue, oddly enough.

**Comment by devipasigner** [comment]
> I have Snowboard installed on Dopamine and I don't have that issue, oddly enough.

Could it have to do with rootful/rootless version of the tweak? I am on rootful. If I remember correctly, I did not have this issue in my 5 minutes testing rootless

**Comment by NightwindDev** [comment]
It might be, not sure though :/
